# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8442c5bb6e670f8549458b4dbd48f5832a738cee0aa4e0a775e0750780c870c1176ae8d2ebf1f9c8e954898d29f509809fad76eb349f8654e28632f374fc205a

test:
  secret_key_base: e99b086b86bb03fe49a6bc59ce455410130afa5f79557170b7b301b74096e751a25eab619cdfb4d118e22f40a76456170cb91ec88475cbdcb31c4c9deaa5b886

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
